export interface Project {
  key: string;
  title: string;
  category: string;
  thumbnail: string;
  desc: string;
  images: string[];
}

export const projects: Project[] = [
  {
    key: "12-stones",
    title: "12 Stones",
    category: "Residential Community",
    thumbnail: "/images/projects/12-stones/Pool_final_new-scaled.jpg",
    desc: "A contemporary residential community of 98 residences near Jerusalem — harmony, natural materials, serene living.",
    images: [
      "/images/projects/12-stones/GAN_AYALOT_TYPE_A_C2-scaled.jpg",
      "/images/projects/12-stones/Pool_final_new-scaled.jpg",
      "/images/projects/12-stones/Street_final_new-scaled.jpg",
      "/images/projects/12-stones/GAN_AYALOT_TYPE_B_BR-scaled.jpg",
      "/images/projects/12-stones/GAN_AYALOT_TYPE_A_C1-scaled.jpg",
      "/images/projects/12-stones/GAN_AYALOT_TYPE_D-scaled.jpg",
      "/images/projects/12-stones/mF45Lw20-scaled.jpeg",
    ],
  },
  {
    key: "schneller-estate",
    title: "Schneller Estate",
    category: "Heritage Estate",
    thumbnail: "/images/projects/schneller-estate/shif-67-scaled.jpg",
    desc: "300sqm in Jerusalem's Schneller neighborhood — cedar wood, green onyx, multi-generational elegance.",
    images: [
      "/images/projects/schneller-estate/shif-35-scaled.jpg",
      "/images/projects/schneller-estate/shif-67-scaled.jpg",
      "/images/projects/schneller-estate/shif-62-scaled.jpg",
      "/images/projects/schneller-estate/shif-54-scaled.jpg",
      "/images/projects/schneller-estate/shif-21-1-scaled.jpg",
      "/images/projects/schneller-estate/shif-40-scaled.jpg",
      "/images/projects/schneller-estate/shif-29-1-scaled.jpg",
      "/images/projects/schneller-estate/shif-56-scaled.jpg",
      "/images/projects/schneller-estate/shif-8-scaled.jpg",
      "/images/projects/schneller-estate/shif-48-scaled.jpg",
      "/images/projects/schneller-estate/shif-25-scaled.jpg",
      "/images/projects/schneller-estate/shif-47-scaled.jpg",
      "/images/projects/schneller-estate/shif-2-scaled.jpg",
      "/images/projects/schneller-estate/shif-3-scaled.jpg",
      "/images/projects/schneller-estate/shif-31-scaled.jpg",
    ],
  },
  {
    key: "haturim-01",
    title: "Haturim #01",
    category: "Vacation Apartment",
    thumbnail: "/images/projects/haturim-01/Haturim17668-scaled.jpg",
    desc: "Vacation apartment on Yaffo Street near Machne Yehuda — elegant spaces for family gatherings.",
    images: [
      "/images/projects/haturim-01/Haturim17518-scaled.jpg",
      "/images/projects/haturim-01/Haturim17786-scaled.jpg",
      "/images/projects/haturim-01/Haturim17668-scaled.jpg",
      "/images/projects/haturim-01/Haturim17672-scaled.jpg",
      "/images/projects/haturim-01/Haturim17654-scaled.jpg",
      "/images/projects/haturim-01/Haturim17569-scaled.jpg",
      "/images/projects/haturim-01/Haturim17730-scaled.jpg",
      "/images/projects/haturim-01/Haturim17505-scaled.jpg",
      "/images/projects/haturim-01/Haturim17574-scaled.jpg",
      "/images/projects/haturim-01/Haturim17533-scaled.jpg",
      "/images/projects/haturim-01/Haturim17765-scaled.jpg",
      "/images/projects/haturim-01/Haturim17586-scaled.jpg",
      "/images/projects/haturim-01/Haturim17801-scaled.jpg",
      "/images/projects/haturim-01/Haturim17689-scaled.jpg",
      "/images/projects/haturim-01/Haturim17704-scaled.jpg",
      "/images/projects/haturim-01/Haturim17616-scaled.jpg",
      "/images/projects/haturim-01/Haturim17684-scaled.jpg",
    ],
  },
  {
    key: "bayit-vegan",
    title: "Bayit Vegan",
    category: "Interior Design",
    thumbnail: "/images/projects/bayit-vegan/Abuav12303-scaled.jpg",
    desc: "Interior design balancing warmth, natural light, and meticulous material selection.",
    images: [
      "/images/projects/bayit-vegan/Abuav12303-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12270-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12450-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12562-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12567-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12263-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12257-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12360-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12320-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12285-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12571-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12347-1-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12398-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12198-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12433-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12532-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12533-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12381-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12496-scaled.jpg",
      "/images/projects/bayit-vegan/Abuav12480-scaled.jpg",
    ],
  },
  {
    key: "haturim-02",
    title: "Haturim #02",
    category: "Vacation Apartment",
    thumbnail: "/images/projects/haturim-02/Haturim18509-scaled.jpg",
    desc: "Elegant vacation apartment on Yaffo Street — soft lines, marble, light-filled views of the Holy City.",
    images: [
      "/images/projects/haturim-02/Haturim18509-scaled.jpg",
      "/images/projects/haturim-02/Haturim18418-scaled.jpg",
      "/images/projects/haturim-02/Haturim18607-scaled.jpg",
      "/images/projects/haturim-02/Haturim18455-scaled.jpg",
      "/images/projects/haturim-02/Haturim18597-scaled.jpg",
      "/images/projects/haturim-02/Haturim18480-scaled.jpg",
      "/images/projects/haturim-02/Haturim18510-scaled.jpg",
      "/images/projects/haturim-02/Haturim18396-scaled.jpg",
      "/images/projects/haturim-02/Haturim18452-scaled.jpg",
      "/images/projects/haturim-02/Haturim18478-scaled.jpg",
      "/images/projects/haturim-02/Haturim18440-scaled.jpg",
      "/images/projects/haturim-02/Haturim18625-scaled.jpg",
      "/images/projects/haturim-02/Haturim18571-1-scaled.jpg",
      "/images/projects/haturim-02/Haturim18573-1-scaled.jpg",
      "/images/projects/haturim-02/Haturim18602-scaled.jpg",
      "/images/projects/haturim-02/Haturim18384-scaled.jpg",
      "/images/projects/haturim-02/Haturim18456-scaled.jpg",
      "/images/projects/haturim-02/Haturim18425-scaled.jpg",
      "/images/projects/haturim-02/Haturim18580-scaled.jpg",
      "/images/projects/haturim-02/Haturim18581-scaled.jpg",
      "/images/projects/haturim-02/Haturim18653-scaled.jpg",
      "/images/projects/haturim-02/Haturim18610-scaled.jpg",
    ],
  },
];
